language: julia
os:
  - linux
  - osx
julia:
  - nightly
  - 0.6
notifications:
  email: change
branches:
  only:
  - master
allow_failures:
  - julia: nightly
addons:
  apt:
    packages:
    - hdf5-tools
